name: Backend-Server-Template
mode: debug
time-zone: local

logger:
    log-level: debug
    log-tag: enable
    
    warn-writer:
        - type: stander
          format: console-try-pretty
          output-path: stdout
        - type: file
          format: file
          output-path: ./example/warn.log
        - type: date-file
          format: file
          output-path: ./example
          file-prefix: warn-date
        - type: date-file
          format: json
          output-path: ./example
          file-prefix: warn-date-machine

    err-writer:
        - type: stander
          format: console-try-pretty
          output-path: stderr
        - type: file
          format: file
          output-path: ./example/error.log
        - type: date-file
          format: file
          output-path: ./example
          file-prefix: error-date
        - type: date-file
          format: json
          output-path: ./example
          file-prefix: error-date-machine
        
signal:
    use-on: not-win32
    sigint-exit: enable
    sigterm-exit: enable
    sighup-exit: enable
    sigquit-exit: enable

win32-console:
    use-on: only-win32
    ctrl-c-exit: enable
    ctrl-break-exit: enable
    console-close-recovery: disable

server:
    name: Jim

    example1:
        stop-wait-time: 10s
        startup-wait-time: 3s
        lock-thread: disable

    example2:
        stop-wait-time: 10s
        startup-wait-time: 3s
        lock-thread: disable

    example3:
        stop-wait-time: 10s
        startup-wait-time: 3s
        lock-thread: disable

    controller:
        stop-wait-time: 10s
        stop-wait-time-use-specified-value: disable
        startup-wait-time: 3s
        startup-wait-time-use-specified-value: disable
        lock-thread: disable
