name: Backend-Server-Template
mode: debug
time-zone: ""
logger:
    log-name: ""
    log-level: debug
    log-tag: enable
    warn-writer:
        write-to-std: stdout
        write-to-file: ""
        write-to-dir-with-date: ""
        write-with-date-prefix: ""
    error-writer:
        write-to-std: stdout
        write-to-file: ""
        write-to-dir-with-date: ""
        write-with-date-prefix: ""
signal:
    sigint-exit: enable
    sigterm-exit: enable
    sighup-exit: enable
    sigquit-exit: ""
server:
    stop-wait-time: 10s
