name: Check And Publish Golang Project
permissions:
  contents: read

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'   # 匹配所有标签
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - master

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4' # 根据需要指定Go版本

      - name: Download module
        run: GOOS=linux GOARCH=amd64 go mod tidy

      - name: Go generate
        run: GOOS=linux GOARCH=amd64 go generate ./...

      - name: Test
        run: GOOS=linux GOARCH=amd64 go test ./...

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4' # 根据需要指定Go版本

      - name: Download module
        run: |
          set GOOS=windows
          set GOARCH=amd64
          go mod tidy

      - name: Go generate
        run: |
          set GOOS=windows
          set GOARCH=amd64
          go generate ./...

      - name: Test
        run:  |
          set GOOS=windows
          set GOARCH=amd64
          go test ./...

  build-ubuntu:
    runs-on: ubuntu-latest
    needs:
      - test-ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4' # 根据需要指定Go版本

      - name: Download module
        run: GOOS=linux GOARCH=amd64 go mod tidy

      - name: Go generate
        run: GOOS=linux GOARCH=amd64 go generate ./...

      - name: Build lionv1
        run: |
          GOOS=linux GOARCH=amd64 go build -o "${{ github.workspace }}/output/linux_amd64_lionv1" -trimpath -ldflags='-s -w -extldflags "-static"' github.com/SongZihuan/BackendServerTemplate/src/cmd/lionv1

      - name: Build tigerv1
        run: |
          GOOS=linux GOARCH=amd64 go build -o "${{ github.workspace }}/output/linux_amd64_tigerv1" -trimpath -ldflags='-s -w -extldflags "-static"' github.com/SongZihuan/BackendServerTemplate/src/cmd/tigerv1

      - name: Build catv1
        run: |
          GOOS=linux GOARCH=amd64 go build -o "${{ github.workspace }}/output/linux_amd64_catv1" -trimpath -ldflags='-s -w -extldflags "-static"' github.com/SongZihuan/BackendServerTemplate/src/cmd/catv1

      - name: List build directory
        run: |
          ls -l "${{ github.workspace }}/output"

      - name: Upload ubuntu artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux_amd64_executable_files
          path: "${{ github.workspace }}/output/"
          if-no-files-found: error

  build-windows:
    runs-on: windows-latest
    needs:
      - test-windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4' # 根据需要指定Go版本

      - name: Download module
        run:  |
          set GOOS=windows
          set GOARCH=amd64
          go mod tidy

      - name: Go generate
        run:  |
          set GOOS=windows
          set GOARCH=amd64
          go generate ./...

      - name: Build lionv1
        run: |
          set GOOS=windows
          set GOARCH=amd64
          go build -o "${{ github.workspace }}/output/windows_amd64_lionv1.exe" -trimpath -ldflags='-s -w -extldflags "-static"' github.com/SongZihuan/BackendServerTemplate/src/cmd/lionv1

      - name: Build tigerv1
        run:  |
          set GOOS=windows
          set GOARCH=amd64
          go build -o "${{ github.workspace }}/output/windows_amd64_tigerv1.exe" -trimpath -ldflags='-s -w -extldflags "-static"' github.com/SongZihuan/BackendServerTemplate/src/cmd/tigerv1

      - name: Build catv1
        run:  |
          set GOOS=windows
          set GOARCH=amd64
          go build -o "${{ github.workspace }}/output/windows_amd64_catv1.exe" -trimpath -ldflags='-s -w -extldflags "-static"' github.com/SongZihuan/BackendServerTemplate/src/cmd/catv1

      - name: List build directory
        run: |
          ls -l "${{ github.workspace }}/output"

      - name: Upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_amd64_executable_files
          path: "${{ github.workspace }}/output/"
          if-no-files-found: error

  create_release:
    runs-on: ubuntu-latest
    needs:
      - build-ubuntu
      - build-windows
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有历史记录以便能够创建标签

      - name: Extract tag name
        id: extract_tag
        run: |
          # 提取标签名
          TAG_NAME=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\///')
          echo "tag=${TAG_NAME}" >> $GITHUB_OUTPUT

      - name: Download ubuntu artifact
        uses: actions/download-artifact@v4
        with:
          name: linux_amd64_executable_files
          path: ${{ github.workspace }}/output

      - name: Download windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows_amd64_executable_files
          path: ${{ github.workspace }}/output

      - name: List directory
        run: ls -l ${{ github.workspace }}/output

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/output/linux_amd64_lionv1,${{ github.workspace }}/output/linux_amd64_tigerv1,${{ github.workspace }}/output/linux_amd64_catv1,${{ github.workspace }}/output/windows_amd64_lionv1.exe,${{ github.workspace }}/output/windows_amd64_tigerv1.exe,${{ github.workspace }}/output/windows_amd64_catv1.exe"
          artifactErrorsFailBuild: true
          allowUpdates: false
          body: |
            新版本 ${{  steps.extract_tag.outputs.tag  }} 发布啦！
            快来体验吧！
          generateReleaseNotes: true
          makeLatest: "legacy"
          tag: "${{  github.ref  }} "
          name: "版本 ${{  steps.extract_tag.outputs.tag  }} 发布！"

      - name: Output the URL of the new release
        run: echo "The release is available at ${{ steps.create_release.outputs.html_url }}"
    outputs:
      tag: "${{  steps.extract_tag.outputs.tag  }}"
      release: "${{ steps.create_release.outputs.html_url }}"
