name: Check And Test
permissions:
  contents: read

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - master

jobs:
  test-linux:
    runs-on: linux-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4' # 根据需要指定Go版本

      - name: Go download dependencies
        run: go mod tidy

      - name: Go generate
        run: go generate ./...

      - name: Go test
        run: go test ./...

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4' # 根据需要指定Go版本

      - name: Go download dependencies
        run: go mod tidy

      - name: Go generate
        run: go generate .\...

      - name: Go test
        run: go test .\...
